BuscadorSemantico: util.DocumentsData Class Reference
util.DocumentsData Class Reference
Static Public Member Functions
static DocumentResult searchAuthorAndSource (String caminhoDocumento)
static int approachingInitialIndex (String texto, int posicao)
static int endIndex (String texto, int posicao)
Detailed Description
Definition at line 9 of file DocumentsData.java.
Member Function Documentation
approachingInitialIndex()
static int util.DocumentsData.approachingInitialIndex (String texto, int posicao) static
Definition at line 34 of file DocumentsData.java.
Referenced by controlador.SemanticsSearch.documentSearch().
endIndex()
static int util.DocumentsData.endIndex (String texto, int posicao) static
Definition at line 45 of file DocumentsData.java.
Referenced by controlador.SemanticsSearch.documentSearch().
searchAuthorAndSource()
static DocumentResult util.DocumentsData.searchAuthorAndSource (String caminhoDocumento) static
Definition at line 10 of file DocumentsData.java.
References DAO.Neo4j.disconnect(), and DAO.Neo4j.getSession().
Referenced by controlador.SemanticsSearch.documentSearch().
The documentation for this class was generated from the following file:
util/DocumentsData.java