BuscadorSemantico: DAO.File Class Reference
DAO.File Class Reference
Static Public Member Functions
static String readFile (String path) throws ErrorFileException
static String readPrefixedFile (String path) throws ErrorFileException
static void writeFile (String path, String text) throws IOException
static java.io.File [] listFiles ()
Detailed Description
Intermedia as operações de leitura e escrita no disco.
Author
Geovani Celebrim
Definition at line 18 of file File.java.
Member Function Documentation
listFiles()
static java.io.File [] DAO.File.listFiles () static
Lista os arquivos do diretório fixado em Authentication.
Returns
File[] que é um array de nomes de arquivos contidos no diretório fixado.
Definition at line 113 of file File.java.
References DAO.Paths.DATA_TEXT, and DAO.Paths.FOLDER.
Referenced by controlador.SimpleSearch.simpleSearch().
readFile()
static String DAO.File.readFile (String path) throws ErrorFileException static
Lê o arquivo passado por parâmetro e retorna uma String com o seu conteúdo.
Parameters
path que é uma String o contendo caminho do arquivo.
Returns
String contendo as informações internas do arquivo.
Exceptions
ErrorFileException informando que não foi possível realizar a leitura do arquivo.
Definition at line 30 of file File.java.
Referenced by DAO.Neo4j_Rest.rest_query().
readPrefixedFile()
static String DAO.File.readPrefixedFile (String path) throws ErrorFileException static
Lê o arquivo passado por parâmetro, que se localiza em um diretório prefixado em Authentication e retorna uma String com o seu conteúdo.
Parameters
path que é uma String contendo o nome do arquivo.
Returns
String contendo as informações internas do arquivo.
Exceptions
ErrorFileException informando que não foi possível realizar a leitura do arquivo.
Definition at line 63 of file File.java.
References DAO.Paths.DATA_TEXT.
Referenced by controlador.SemanticsSearch.documentSearch(), and controlador.servlets.PaginaResultados.processarRequisicao().
writeFile()
static void DAO.File.writeFile (String path, String text) throws IOException static
Escreve no arquivo passado por parâmetro, o texto, também passado por parâmetro. Caso não seja possível realizar a escrita, é lançada uma excessão.
Parameters
path que é o caminho e nome do arquivo.
text que é o texto a ser escrito no arquivo.
Exceptions
IOException caso não seja possível a escrita.
Definition at line 98 of file File.java.
Referenced by DAO.Neo4j_Rest.rest_query().
The documentation for this class was generated from the following file:
DAO/File.java