BuscadorSemantico: controlador.SimpleSearch Class Reference
controlador.SimpleSearch Class Reference
Static Public Member Functions
static ArrayList< SimpleResults > simpleSearch (String keyWords) throws ErrorFileException
Static Private Member Functions
static String searchAuthor (String documentName)
static String searchSource (String documentName)
Detailed Description
Controlador responsável por mediar as buscas por palavra chave no banco e no repositório de arquivos.
Author
Geovani Celebrim
Definition at line 21 of file SimpleSearch.java.
Member Function Documentation
searchAuthor()
static String controlador.SimpleSearch.searchAuthor (String documentName) static private
Busca um autor de um documento passado por parâmetro no banco.
Parameters
documentName String contendo o nome do documento.
Returns
String contendo o nome do autor.
Definition at line 64 of file SimpleSearch.java.
References DAO.Neo4j.disconnect(), and DAO.Neo4j.getSession().
Referenced by controlador.SimpleSearch.simpleSearch().
searchSource()
static String controlador.SimpleSearch.searchSource (String documentName) static private
Busca a fonte de um documento passado por parâmetro no banco.
Parameters
documentName String contendo o nome do documento.
Returns
String contendo o nome da fonte.
Definition at line 91 of file SimpleSearch.java.
References DAO.Neo4j.disconnect(), and DAO.Neo4j.getSession().
Referenced by controlador.SimpleSearch.simpleSearch().
simpleSearch()
static ArrayList<SimpleResults> controlador.SimpleSearch.simpleSearch (String keyWords) throws ErrorFileException static
Realiza uma busca simples por palavra chave nos documentos do repositório.
Parameters
keyWords String da busca.
Returns
ArrayList de SimpleResults.
Exceptions
ErrorFileException caso ocorra erro na leitura dos arquivos.
Definition at line 31 of file SimpleSearch.java.
References DAO.File.listFiles(), controlador.SimpleSearch.searchAuthor(), and controlador.SimpleSearch.searchSource().
Referenced by controlador.servlets.PaginaPrincipal.processarRequisicao(), and controlador.servlets.PaginaResultados.processarRequisicao().
The documentation for this class was generated from the following file:
controlador/SimpleSearch.java