BuscadorSemantico: DAO.Neo4j Class Reference
DAO.Neo4j Class Reference
Public Member Functions
Neo4j ()
Session getSession ()
void disconnect ()
Private Attributes
Driver driver
Session session
Detailed Description
Responsável por realizar as conexções com o banco através do bolt.
Author
Geovani Celebrim
Definition at line 14 of file Neo4j.java.
Constructor & Destructor Documentation
Neo4j()
DAO.Neo4j.Neo4j ()
O construtor inicializa uma conexão com o banco, para que seja realizada uma consulta.
Definition at line 24 of file Neo4j.java.
References DAO.Authentication.PASSWORD, and DAO.Authentication.USER.
Member Function Documentation
disconnect()
void DAO.Neo4j.disconnect ()
Finaliza a conexção com o banco.
Definition at line 43 of file Neo4j.java.
Referenced by controlador.SemanticsSearch.cypherSearchBolt(), controlador.SimpleSearch.searchAuthor(), util.DocumentsData.searchAuthorAndSource(), and controlador.SimpleSearch.searchSource().
getSession()
Session DAO.Neo4j.getSession ()
Obtém a instância da sessão atual do banco.
Returns
Session.
Definition at line 36 of file Neo4j.java.
References DAO.Neo4j.session.
Referenced by controlador.SemanticsSearch.cypherSearchBolt(), controlador.SimpleSearch.searchAuthor(), util.DocumentsData.searchAuthorAndSource(), and controlador.SimpleSearch.searchSource().
Member Data Documentation
driver
Driver DAO.Neo4j.driver private
Definition at line 16 of file Neo4j.java.
session
Session DAO.Neo4j.session private
Definition at line 18 of file Neo4j.java.
Referenced by DAO.Neo4j.getSession().
The documentation for this class was generated from the following file:
DAO/Neo4j.java