BuscadorSemantico: DAO.Neo4j_Rest Class Reference
DAO.Neo4j_Rest Class Reference
Static Public Member Functions
static Graph getGraph (String query) throws ErrorFileException, IOException
Static Private Member Functions
static String rest_query (String query) throws ErrorFileException, IOException
static Graph builderGraph (String response)
Detailed Description
Responsável por realizar as conexções com o banco usando REST.
Author
Geovani Celebrim
Definition at line 16 of file Neo4j_Rest.java.
Member Function Documentation
builderGraph()
static Graph DAO.Neo4j_Rest.builderGraph (String response) static private
Constroi um grafo com o JSON retornado do banco.
Parameters
response que é o que o banco retorna através do método rest_query da classe Neo4j_Rest.
Returns
Graph construido a partir do response.
Definition at line 54 of file Neo4j_Rest.java.
References entidade.Graph.addEdge(), and entidade.Graph.adicionarVertice().
Referenced by DAO.Neo4j_Rest.getGraph().
getGraph()
static Graph DAO.Neo4j_Rest.getGraph (String query) throws ErrorFileException, IOException static
Retorna um grafo, dada uma query em Cypher.
Parameters
query String no formato Cypher.
Returns
Graph.
Exceptions
ErrorFileException caso ocorra erro nos métodos dependentes.
IOException caso ocorra erro nos métodos dependentes.
Definition at line 86 of file Neo4j_Rest.java.
References DAO.Neo4j_Rest.builderGraph(), and DAO.Neo4j_Rest.rest_query().
Referenced by controlador.SemanticsSearch.buscaCypherRest().
rest_query()
static String DAO.Neo4j_Rest.rest_query (String query) throws ErrorFileException, IOException static private
Sobrescreve um template em Python e realiza uma conexão com o banco para obter o JSON.
Parameters
query que é a consulta em Cypher a ser realizada.
Returns
String com o JSON que representa um grafo.
Exceptions
ErrorFileException caso ocorra algum erro na sobrescrita.
IOException caso ocorra algum erro na sobrescrita.
Definition at line 24 of file Neo4j_Rest.java.
References util.Sys.command(), DAO.Authentication.PASSWORD, DAO.File.readFile(), DAO.Paths.REST, DAO.Authentication.USER, and DAO.File.writeFile().
Referenced by DAO.Neo4j_Rest.getGraph().
The documentation for this class was generated from the following file:
DAO/Neo4j_Rest.java