BuscadorSemantico: controlador.servlets.PaginaPrincipal Class Reference
controlador.servlets.PaginaPrincipal Class Reference
Public Member Functions
PaginaPrincipal ()
Protected Member Functions
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
void doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Private Member Functions
void processarRequisicao (HttpServletRequest request, HttpServletResponse response) throws ServletException
void irParaResultadosSemanticos (HttpServletRequest request, HttpServletResponse response)
void irParaResultadosSimples (HttpServletRequest request, HttpServletResponse response)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 21 of file PaginaPrincipal.java.
Constructor & Destructor Documentation
PaginaPrincipal()
controlador.servlets.PaginaPrincipal.PaginaPrincipal ()
Definition at line 24 of file PaginaPrincipal.java.
Member Function Documentation
doGet()
void controlador.servlets.PaginaPrincipal.doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
Definition at line 132 of file PaginaPrincipal.java.
doPost()
void controlador.servlets.PaginaPrincipal.doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
Definition at line 138 of file PaginaPrincipal.java.
irParaResultadosSemanticos()
void controlador.servlets.PaginaPrincipal.irParaResultadosSemanticos (HttpServletRequest request, HttpServletResponse response) private
Definition at line 104 of file PaginaPrincipal.java.
irParaResultadosSimples()
void controlador.servlets.PaginaPrincipal.irParaResultadosSimples (HttpServletRequest request, HttpServletResponse response) private
Definition at line 118 of file PaginaPrincipal.java.
processarRequisicao()
void controlador.servlets.PaginaPrincipal.processarRequisicao (HttpServletRequest request, HttpServletResponse response) throws ServletException private
Definition at line 28 of file PaginaPrincipal.java.
References controlador.SemanticsSearch.buscaCypherRest(), controlador.SemanticsSearch.cypherSearchBolt(), controlador.SemanticsSearch.documentSearch(), and controlador.SimpleSearch.simpleSearch().
Member Data Documentation
serialVersionUID
final long controlador.servlets.PaginaPrincipal.serialVersionUID = 1L static private
Definition at line 22 of file PaginaPrincipal.java.
The documentation for this class was generated from the following file:
controlador/servlets/PaginaPrincipal.java