BuscadorSemantico: controlador.servlets.PaginaResultados Class Reference
controlador.servlets.PaginaResultados Class Reference
Public Member Functions
PaginaResultados ()
Protected Member Functions
void doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
void doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
Private Member Functions
void processarRequisicao (HttpServletRequest request, HttpServletResponse response) throws ServletException
void irParaResultadosSimples (HttpServletRequest request, HttpServletResponse response)
void irParaResultadosSemanticos (HttpServletRequest request, HttpServletResponse response)
void irParaDocumento (HttpServletRequest request, HttpServletResponse response)
Static Private Attributes
static final long serialVersionUID = 1L
Detailed Description
Definition at line 22 of file PaginaResultados.java.
Constructor & Destructor Documentation
PaginaResultados()
controlador.servlets.PaginaResultados.PaginaResultados ()
Definition at line 25 of file PaginaResultados.java.
Member Function Documentation
doGet()
void controlador.servlets.PaginaResultados.doGet (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
Definition at line 181 of file PaginaResultados.java.
doPost()
void controlador.servlets.PaginaResultados.doPost (HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException protected
Definition at line 186 of file PaginaResultados.java.
irParaDocumento()
void controlador.servlets.PaginaResultados.irParaDocumento (HttpServletRequest request, HttpServletResponse response) private
Definition at line 167 of file PaginaResultados.java.
irParaResultadosSemanticos()
void controlador.servlets.PaginaResultados.irParaResultadosSemanticos (HttpServletRequest request, HttpServletResponse response) private
Definition at line 153 of file PaginaResultados.java.
irParaResultadosSimples()
void controlador.servlets.PaginaResultados.irParaResultadosSimples (HttpServletRequest request, HttpServletResponse response) private
Definition at line 139 of file PaginaResultados.java.
processarRequisicao()
void controlador.servlets.PaginaResultados.processarRequisicao (HttpServletRequest request, HttpServletResponse response) throws ServletException private
Definition at line 29 of file PaginaResultados.java.
References controlador.SemanticsSearch.buscaCypherRest(), controlador.SemanticsSearch.cypherSearchBolt(), controlador.SemanticsSearch.documentSearch(), DAO.File.readPrefixedFile(), and controlador.SimpleSearch.simpleSearch().
Member Data Documentation
serialVersionUID
final long controlador.servlets.PaginaResultados.serialVersionUID = 1L static private
Definition at line 23 of file PaginaResultados.java.
The documentation for this class was generated from the following file:
controlador/servlets/PaginaResultados.java