BuscadorSemantico: controlador.SemanticsSearch Class Reference
controlador.SemanticsSearch Class Reference
Static Public Member Functions
static ArrayList< cypherResults > cypherSearchBolt (String cypherQuery) throws Exception
static Graph buscaCypherRest (String query)
static ArrayList< DocumentResult > documentSearch (String cypherQuery) throws Exception
Detailed Description
Controlador responsável por mediar as buscas semânticas no banco e no repositório de arquivos.
Author
Geovani Celebrim
Definition at line 27 of file SemanticsSearch.java.
Member Function Documentation
buscaCypherRest()
static Graph controlador.SemanticsSearch.buscaCypherRest (String query) static
Realiza uma busca no banco Neo4j, usando o módulo em Python, dada uma String no formato Cypher, e retorna um Graph.
Parameters
query String em formato Cypher.
Returns
Graph
Definition at line 68 of file SemanticsSearch.java.
References DAO.Neo4j_Rest.getGraph().
Referenced by controlador.servlets.PaginaPrincipal.processarRequisicao(), and controlador.servlets.PaginaResultados.processarRequisicao().
cypherSearchBolt()
static ArrayList<cypherResults> controlador.SemanticsSearch.cypherSearchBolt (String cypherQuery) throws Exception static
Busca no banco Neo4j, dada uma String no formato Cypher, e retorna um ArrayList de cypherResults.
Parameters
cypherQuery String no formato Cypher.
Returns
ArrayList de cypherResults contendo os resultados encontrados.
Exceptions
Exception caso ocorra uma falha em algum passo da busca.
Definition at line 41 of file SemanticsSearch.java.
References DAO.Neo4j.disconnect(), DAO.Neo4j.getSession(), and util.DataProcessing.statementToCypher().
Referenced by controlador.servlets.PaginaPrincipal.processarRequisicao(), and controlador.servlets.PaginaResultados.processarRequisicao().
documentSearch()
static ArrayList<DocumentResult> controlador.SemanticsSearch.documentSearch (String cypherQuery) throws Exception static
Realiza uma busca no banco Neo4j, dada uma String no formato Cypher, e retorna um ArrayList de DocumentResult. Essa busca cruza os dados do banco para obter o trecho onde a informação se encontra no documento.
Parameters
cypherQuery String no formado Cypher.
Returns
ArrayList de DocumentResult.
Exceptions
Exception caso ocorra algum erro na extração dos dados.
Definition at line 104 of file SemanticsSearch.java.
References util.DocumentsData.approachingInitialIndex(), util.DataProcessing.crossData(), util.DocumentsData.endIndex(), entidade.resultados.DocumentResult.getAuthor(), entidade.resultados.DocumentResult.getSource(), DAO.File.readPrefixedFile(), and util.DocumentsData.searchAuthorAndSource().
Referenced by controlador.servlets.PaginaPrincipal.processarRequisicao(), and controlador.servlets.PaginaResultados.processarRequisicao().
The documentation for this class was generated from the following file:
controlador/SemanticsSearch.java