BuscadorSemantico: DAO.Authentication Enum Reference
DAO.Authentication Enum Reference
Public Member Functions
String toString ()
Public Attributes
USER =("neo4j")
PASSWORD =("cedim")
Private Member Functions
Authentication (final String text)
Private Attributes
final String text
Detailed Description
Esta classe tem como finalidade informar o usuário e senha do banco para o sistema. O principal objetivo é centralizar as alterações, para que, caso necessário, essas informações sejam alteradas em apenas um local.
Author
Geovani Celebrim
Definition at line 10 of file Authentication.java.
Constructor & Destructor Documentation
Authentication()
DAO.Authentication.Authentication (final String text) private
Definition at line 23 of file Authentication.java.
Member Function Documentation
toString()
String DAO.Authentication.toString ()
Pega o valor relacionado ao Enum em questão.
Returns
String contendo o valor associado ao Enum.
See also
java.lang.Enum::toString()
Enum
Definition at line 36 of file Authentication.java.
Member Data Documentation
PASSWORD
DAO.Authentication.PASSWORD =("cedim")
Enum que representa a senha do banco.
Definition at line 19 of file Authentication.java.
Referenced by DAO.Neo4j.Neo4j(), and DAO.Neo4j_Rest.rest_query().
text
final String DAO.Authentication.text private
Definition at line 21 of file Authentication.java.
USER
DAO.Authentication.USER =("neo4j")
Enum que representa o usuário do banco.
Definition at line 14 of file Authentication.java.
Referenced by DAO.Neo4j.Neo4j(), and DAO.Neo4j_Rest.rest_query().
The documentation for this enum was generated from the following file:
DAO/Authentication.java