BuscadorSemantico: DAO.Paths Enum Reference
DAO.Paths Enum Reference
Public Member Functions
String toString ()
Public Attributes
DATA_TEXT =("/home/geovani/cedim-data/")
FOLDER =("/CEDIM-II-GUERRA")
REST =("/home/geovani/git/tcc/BuscadorSemantico/rest/")
Private Member Functions
Paths (final String text)
Private Attributes
final String text
Detailed Description
Esta classe tem como finalidade informar os diretórior de arquivos utilizados no sistema. O principal objetivo é centralizar as alterações, para que, caso necessário, essas informações sejam alteradas em apenas um local.
Author
Geovani Celebrim
Definition at line 10 of file Paths.java.
Constructor & Destructor Documentation
Paths()
DAO.Paths.Paths (final String text) private
Definition at line 34 of file Paths.java.
Member Function Documentation
toString()
String DAO.Paths.toString ()
Pega o valor relacionado ao Enum em questão.
Returns
String contendo o valor associado ao Enum.
See also
java.lang.Enum::toString()
Enum
Definition at line 47 of file Paths.java.
Member Data Documentation
DATA_TEXT
DAO.Paths.DATA_TEXT =("/home/geovani/cedim-data/")
Enum que representa o diretório de arquivos de texto retornados nas buscas.
Definition at line 16 of file Paths.java.
Referenced by DAO.File.listFiles(), and DAO.File.readPrefixedFile().
FOLDER
DAO.Paths.FOLDER =("/CEDIM-II-GUERRA")
Enum que representa a pasta dos dados utilizados no protótipo.
Definition at line 23 of file Paths.java.
Referenced by DAO.File.listFiles().
REST
DAO.Paths.REST =("/home/geovani/git/tcc/BuscadorSemantico/rest/")
Enum que representa o diretório do módulo em Python utilizado para conexão REST
Definition at line 29 of file Paths.java.
Referenced by DAO.Neo4j_Rest.rest_query().
text
final String DAO.Paths.text private
Definition at line 32 of file Paths.java.
The documentation for this enum was generated from the following file:
DAO/Paths.java